version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - unconvert
    - bodyclose

  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
